services:
  db:
    image: postgres:16-alpine
    container_name: sitd-db
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./api
    container_name: sitd-api
    restart: unless-stopped
    env_file: .env
    environment:
      # Aun si viniera mal (+psycopg), db.py lo corrige a +psycopg2
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  web:
    build:
      context: ./web
    container_name: sitd-web
    restart: unless-stopped
    environment:
      VITE_API_URL: "http://localhost:8000"
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules

volumes:
  db_data:
