"""add useful indexes

Revision ID: 9362924715bc
Revises: 1886717fe8be
Create Date: 2025-10-23 18:53:04.399228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9362924715bc'
down_revision: Union[str, None] = '1886717fe8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comercios_creado_en'), 'comercios', ['creado_en'], unique=False)
    op.create_index('ix_comercios_creado_en_desc', 'comercios', ['creado_en'], unique=False)
    op.create_index(op.f('ix_comercios_id'), 'comercios', ['id'], unique=False)
    op.create_index(op.f('ix_comercios_nombre'), 'comercios', ['nombre'], unique=False)
    op.create_index(op.f('ix_eventos_comercio_id'), 'eventos', ['comercio_id'], unique=False)
    op.create_index(op.f('ix_eventos_creado_en'), 'eventos', ['creado_en'], unique=False)
    op.create_index('ix_eventos_creado_en_desc', 'eventos', ['creado_en'], unique=False)
    op.create_index(op.f('ix_eventos_fecha_fin'), 'eventos', ['fecha_fin'], unique=False)
    op.create_index(op.f('ix_eventos_fecha_inicio'), 'eventos', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_eventos_id'), 'eventos', ['id'], unique=False)
    op.create_index('ix_eventos_rango', 'eventos', ['fecha_inicio', 'fecha_fin'], unique=False)
    op.create_index(op.f('ix_eventos_titulo'), 'eventos', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_titulo'), table_name='eventos')
    op.drop_index('ix_eventos_rango', table_name='eventos')
    op.drop_index(op.f('ix_eventos_id'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_fecha_inicio'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_fecha_fin'), table_name='eventos')
    op.drop_index('ix_eventos_creado_en_desc', table_name='eventos')
    op.drop_index(op.f('ix_eventos_creado_en'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_comercio_id'), table_name='eventos')
    op.drop_index(op.f('ix_comercios_nombre'), table_name='comercios')
    op.drop_index(op.f('ix_comercios_id'), table_name='comercios')
    op.drop_index('ix_comercios_creado_en_desc', table_name='comercios')
    op.drop_index(op.f('ix_comercios_creado_en'), table_name='comercios')
    # ### end Alembic commands ###
